#!/bin/sh

# docker run -v $(pwd):/home/godev:z -e GODEV_UID=$(id -u) --rm -ti fedora:28 /bin/bash
# docker run -v $(pwd):/home/godev:z -e GODEV_UID=$(id -u) --rm -ti golang:1.10-alpine /bin/sh

# host networking (--network host)
# https://docs.docker.com/network/host/
# "The host networking driver only works on Linux hosts, and is not supported on Docker for Mac, Docker for Windows, or Docker EE for Windows Server."

docker run  -v $(pwd):/home/godev:z --security-opt seccomp=unconfined -e GODEV_UID=$(id -u) --rm -ti --network host godev:1.10-alpine /bin/bash "$@"
